### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원 가입
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "",
  "email": "zxc@gmail.com",
  "password": "Abcd1234!"
}