### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원 가입
POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "",
  "email": "test1@gmail.com",
  "password": "Test1234!"
}

### 회원 가입
POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "",
  "email": "test2@gmail.com",
  "password": "Test2345!"
}

### 회원 가입
POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "",
  "email": "test3@gmail.com",
  "password": "Test3456!"
}

### 로그인
POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "Test1234!"
}