### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원 가입
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "",
  "email": "zxc@gmail.com",
  "password": "Abcd1234!"
}

### 로그인
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "email": "zxc@gmail.com",
  "password": "Abcd12345!"
}

### 비밀번호 재설정
PUT http://localhost:8080/auth/password
Content-Type: application/json
Authorization: Bearer


{
  "currentPassword": "Abcd1234!",
  "newPassword": "Abcd12345!"
}