### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 비밀번호 재설정
PATCH http://localhost:8080/users/password
Content-Type: application/json
Authorization: Bearer

{
  "currentPassword": "Test1234!",
  "newPassword": "Test12345!"
}

### 회원 탈퇴
PATCH http://localhost:8080/users/deactivate
Content-Type: application/json
Authorization: Bearer

{
  "currentPassword": "Test1234!"
}

### 사용자 정보 조회
GET http://localhost:8080/users/me
Authorization: Bearer

### 사용자 정보 수정 (현재는 닉네임만 가능)
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Bearer

{
  "nickname": "changeNickname"
}