spring:
  port: 8080

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  server:
    use-forward-headers: true
    tomcat:
      connection-timeout: 60s
      max-swallow-size: -1 # Tomcat 업로드 파일 크기 제한 해제

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
cloud:
  aws:
    region: ${cloud.aws.region}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    s3:
      bucket-name: ${cloud.aws.s3.bucket-name}
      video-prefix: 'videos/'
      image-prefix: 'images/'

logging:
  level:
    root: INFO  # 기본 로그 레벨 설정 (전체 애플리케이션의 기본 로그 레벨)
    org.springframework.security: DEBUG  # Spring Security 관련 로그를 DEBUG로 설정
    org.springframework.web: DEBUG  # Spring Web 관련 로그를 DEBUG로 설정
    com.sudurukbackback.modulecture: DEBUG  # 프로젝트 내 로그를 DEBUG로 설정 (필요시)
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 콘솔 로그 출력 포맷 설정
  file:
    name: "logs/application.log"  # 로그 파일 위치 및 이름 설정
    max-size: 10MB  # 로그 파일 크기 제한
    max-history: 30  # 최대 로그 보관 일수
    total-size-cap: 100MB  # 최대 로그 파일 크기 설정
