spring:
  port: 8080

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  server:
    tomcat:
      connection-timeout: 60s
      max-swallow-size: -1 # Tomcat 업로드 파일 크기 제한 해제

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  # Naver OAuth2
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${naver.client-id}
            client-secret: ${naver.client-secret}
            redirect-uri: ${naver.redirect-uri}
            authorization-grant-type: ${naver.auth-grant-type}
            scope: email

          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            redirect-uri: ${google.redirect-uri}
            scope:
              - email
              - profile

        provider:
          naver:
            authorization-uri: ${naver.auth-uri}
            token-uri: ${naver.token-uri}
            user-info-uri: ${naver.user-info-uri}
            user-name-attribute: ${naver.user-name-attribute}

          google:
            authorization-uri: ${google.auth-uri}
            token-uri: ${google.token-uri}
            user-info-uri: ${google.user-info-uri}
            jwk-set-uri: ${google.jwt-set-uri}
            user-name-attribute: ${google.user-name-attribute}

cloud:
  aws:
    region: ${cloud.aws.region}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    s3:
      bucket-name: ${cloud.aws.s3.bucket-name}
      video-prefix: 'videos/'
      image-prefix: 'images/'
