spring:
  port: 8080

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  server:
    tomcat:
      connection-timeout: 60s
      max-swallow-size: -1 # Tomcat 업로드 파일 크기 제한 해제

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
  
cloud:
  aws:
    region: ${cloud.aws.region}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    s3:
      bucket-name: ${cloud.aws.s3.bucket-name}
      video-prefix: 'videos/'
      image-prefix: 'images/'